services:
  - type: web
    name: rocketchat
    env: docker
    repo: https://github.com/DesignersInborn/Docker.Official.Image
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: >
      bash -c 'export PORT=$PORT && export MONGO_URL=$MONGO_URL && export MONGO_OPLOG_URL=$MONGO_OPLOG_URL && export ROOT_URL=$ROOT_URL && node main.js'
    envVars:
      - key: ROOT_URL
        value: https://rocket-chatdesignersinborn.onrender.com
      - key: PORT
        value: 3000
      - key: MONGO_URL
        value: mongodb+srv://designersinbornadmin:wNPH0LqYdEqml4L3@rocketchatdesignersinbo.2jfyyze.mongodb.net/rocketchat?retryWrites=true&w=majority&appName=RocketChatDesignersInborn
      - key: MONGO_OPLOG_URL
        value: mongodb+srv://designersinbornadmin:wNPH0LqYdEqml4L3@rocketchatdesignersinbo.2jfyyze.mongodb.net/local?retryWrites=true&w=majority&appName=RocketChatDesignersInborn
    autoDeploy: true
